dethrace-labs/dethrace

- src/BRSRC13/CORE/STD/stdlib.c
- src/BRSRC13/CORE/STD/stdlib.h
Might be worth considering renaming these to avoid conflict with C lib stdlib.h.
> Implements stdblib.c functions.

- src/BRSRC13/CORE/FW/diag.c
- src/BRSRC13/CORE/FW/fwsetup.h
- src/BRSRC13/CORE/STD/stdfile.c
- src/BRSRC13/CORE/STD/stdlib.c
- src/BRSRC13/CORE/STD/stdlib.h
- src/BRSRC13/CORE/STD/stdmem.c
- src/DETHRACE/source/common/controls.c
- src/DETHRACE/source/common/errors.c
- src/DETHRACE/source/common/errors.h
- src/DETHRACE/source/common/piping.c
- src/DETHRACE/source/common/powerup.c
- src/DETHRACE/source/common/world.c
- src/types/br_types.h
- src/types/dr_types.h
Not all of the changes will be strictly correct, but is the minimum I needed to do to get it to build the brender code on ubuntu 18.04.
> Implements minimum changes to get BRender files to compile.

- Makefile
- run.sh
- src/DETHRACE/common/brucetrk.c
- src/DETHRACE/common/crush.c
- src/DETHRACE/common/depth.c
- src/DETHRACE/common/globvars.c
- src/DETHRACE/common/graphics.c
- src/DETHRACE/common/init.c
- src/DETHRACE/common/loading.c
- src/DETHRACE/common/loadsave.c
- src/DETHRACE/common/main.c
- src/DETHRACE/common/network.c
- src/DETHRACE/common/opponent.c
- src/DETHRACE/common/replay.c
- src/DETHRACE/common/sound.c
- src/DETHRACE/common/spark.c
- src/DETHRACE/common/utility.c
- src/DETHRACE/common/utility.h
- src/DETHRACE/common/world.c
- src/DETHRACE/pc-dos/dosnet.c
- src/DETHRACE/pc-dos/dossys.c
- src/DETHRACE/pc-dos/dossys.h
- test/DETHRACE/test_dossys.c
- test/DETHRACE/test_errors.c
- test/DETHRACE/test_loading.c
- test/DETHRACE/test_utility.c
- test/main.c
Adds previously missed `static` modifiers
> Implements GameMain initialization

- src/DETHRACE/common/cutscene.c
- src/DETHRACE/common/graphics.c
- src/DETHRACE/common/loading.c
- src/DETHRACE/common/main.c
- src/DETHRACE/common/sound.c
- src/DETHRACE/main.c
- src/DETHRACE/pc-dos/dossys.c
- src/harness/harness.c
- src/harness/harness.h
CD check code can be enabled by passing `-cdcheck`
> Disable cd check by default, add support for SP/Carma game modes

- src/BRSRC13/CORE/MATH/matrix34.c
- src/BRSRC13/CORE/V1DB/actsupt.c
- src/BRSRC13/br_defs.h
- src/BRSRC13/br_types.h
- src/BRSRC13/brender.h
- src/DETHRACE/common/brucetrk.c
- src/DETHRACE/common/car.c
- src/DETHRACE/common/depth.c
- src/DETHRACE/common/finteray.c
- src/DETHRACE/common/init.c
- src/DETHRACE/common/opponent.c
- src/DETHRACE/common/raycast.c
- src/DETHRACE/common/world.c
Now the swooping starting camera in MAYAN MAHEM track snaps straight to the car because it collides correctly with the tunnel roof...
> Awfully complicated camera collision bits

- src/BRSRC13/CORE/FW/datafile.c
- src/harness/sdl/common.c
For correct build fix 2 error.
> Fix 2 error

- src/harness/harness.c
- tools/progress.py
- Adds `tools/progress.py` which displays the current project completeness. (fixes #55)
- Fixes issue where new command line args were not recognized. (use `--fps=x`, note no spaces) 
Of course, theres a lot of complexity hidden from the tool - we don't know how many of the unimplemented functions we will eventually need to implement (especially on the BRENDER side, many functions are never called, but also plenty in DETHRACE), and also this doesn't complexity of each function.  Still, its interesting to see :)
Most complex DETHRACE files are `common/WORLD.c` (252 functions), followed to `common/CAR.c` (161 functions)
Current output:
```
find src -name "*.c" | xargs ./progress.py
name                                          percent	complete / total
======================================= …
```
> Progress script

- src/DETHRACE/common/loading.c
- src/DETHRACE/common/racestrt.c
As the title suggests, this pr adds the 'change race' dialog
> Add change race dialog

- src/BRSRC13/CORE/FW/file.c
- src/BRSRC13/CORE/V1DB/actsupt.c
- src/DETHRACE/common/graphics.c
- src/DETHRACE/common/loading.c
- src/DETHRACE/common/newgame.c
- src/DETHRACE/common/pedestrn.c
- src/DETHRACE/common/racestrt.c
- src/DETHRACE/common/world.c
This pr adds the "Change Car" dialog (+ required dependencies)
This is a save game for current dethrace that has the game finished flag set:
[SAVE0.zip](https://github.com/dethrace-labs/dethrace/files/8218856/SAVE0.zip)
Extract and save it in the `DATA/SAVEGAME` folder.
> Add change car dialog

- src/BRSRC13/CORE/FW/file.c
- src/BRSRC13/CORE/STD/brstdfile.c
- src/DETHRACE/common/depth.c
- src/DETHRACE/common/flicplay.c
- src/DETHRACE/common/graphics.c
- src/DETHRACE/common/intrface.c
- src/DETHRACE/common/loading.c
- src/DETHRACE/common/mainmenu.c
- src/DETHRACE/common/options.c
- src/DETHRACE/common/racestrt.c
- src/DETHRACE/common/utility.c
- src/DETHRACE/constants.h
- src/DETHRACE/pc-dos/dossys.c
- src/harness/harness.c
- src/harness/include/harness/hooks.h
- src/harness/include/harness/os.h
- src/harness/io_platforms/io_platform.h
- src/harness/io_platforms/sdl_gl.c
- src/harness/os/linux.c
- src/harness/os/macos.c
- src/harness/os/windows.c
This pr:
- adds mouse support
- draws the cursor
- draws giblets (=blood drops)
Fixes #75
> Start To Mouse

- src/DETHRACE/common/graphics.c
> Fixes TellyInImage white dot

- src/BRSRC13/CORE/V1DB/def_mat.c
- src/BRSRC13/CORE/V1DB/v1dbfile.c
- src/DETHRACE/common/world.c
- tools/decode_datatxt.py
This is a collection of changes I made to DethRace while working on rec2 and transcoding some of this code to Python.
Functional difference is 0%.
> Little changes

- src/DETHRACE/common/car.c
> Fix buffer overflow when driving with full speed into noncar thing

- src/DETHRACE/common/car.c
- src/DETHRACE/common/crush.c
- src/DETHRACE/common/displays.c
- src/DETHRACE/common/mainloop.c
- src/DETHRACE/common/opponent.c
- src/DETHRACE/common/oppoproc.c
- src/DETHRACE/common/spark.c
- src/DETHRACE/common/world.c
- Implements credits and time bonus for damaging opponents
- Fixes opponent attack behavior so they actually chase the player now
- Implements cops
https://user-images.githubusercontent.com/78985374/189511446-59e7709a-8aae-4dc9-9167-ada16911b51e.mov
> Aggressive opponents

- src/DETHRACE/common/opponent.c
Resubmit of: https://github.com/dethrace-labs/dethrace/pull/149
thanks to @madebr
> Implements processfrozen

- src/DETHRACE/common/car.c
- src/DETHRACE/common/pratcam.c
- src/DETHRACE/common/sound.c
- src/DETHRACE/common/structur.c
> Implement pratcam

- src/DETHRACE/common/pratcam.c
@madebr could you double check this?
> Fixes NextPratcamChunk

- src/DETHRACE/common/car.c
> Fix bouncing lampposts and other odd physics things

- src/DETHRACE/common/finteray.c
- src/DETHRACE/common/oil.c
- src/DETHRACE/common/raycast.c
- src/DETHRACE/common/raycast.h
> Oil spills

- src/DETHRACE/common/displays.c
- src/DETHRACE/common/powerup.c
Fix amount of credits handed out when getting a credits power-up.
Also fixes a message when losing credits (maybe used in multiplayer?).
Thanks @rafalp
> Fix amount of credits handed out in GotCredits

- src/DETHRACE/common/opponent.c
Found this while going though code
> Fix conditional in CalcRaceRoute

- src/DETHRACE/common/car.c
- src/DETHRACE/common/loading.c
- src/DETHRACE/common/mainloop.c
- src/DETHRACE/common/opponent.c
- src/DETHRACE/common/world.c
The new formatting makes the code more readable, and is functionally the same.
> Various formatting fixes

- src/DETHRACE/common/depth.c
- src/DETHRACE/common/powerup.c
Fixes #204 (horizon being shown incorrectly inside the castle level)
> Implements DoSpecialCameraEffect

- src/DETHRACE/common/crush.c
> cmake: inner loop in DoWheelDamage need only be executed 4 times

- src/BRSRC13/include/brender/brender.h
- src/DETHRACE/CMakeLists.txt
- src/DETHRACE/common/car.c
- src/DETHRACE/common/graphics.c
- src/DETHRACE/common/pedestrn.c
- src/DETHRACE/common/piping.c
- src/DETHRACE/common/replay.c
- src/DETHRACE/common/sound.c
- src/DETHRACE/common/spark.c
- src/DETHRACE/constants.h
- src/DETHRACE/dr_types.h
- src/DETHRACE/macros.h
- src/DETHRACE/pc-dos/dossys.c
- src/S3/include/s3/s3.h
- src/S3/s3sound.c
- src/harness/harness.c
- src/harness/include/harness/config.h
- src/harness/include/harness/os.h
- src/harness/os/linux.c
- src/harness/os/macos.c
- src/harness/os/windows.c
This pr adds action replay.
I have verified the behavior of this code with OG, 
but it acts funny/buggy/crashy when integrated into dethrace.
That's why I have "hidden" action replay behind a `--enable-replay` argument.
> Add action replay

- src/DETHRACE/common/world.c
- src/DETHRACE/constants.h
I noticed some discrepancies with my `PathGrooveBastard`, so here are my suggestions.
> Extra fixes for vehicle suspension

- src/DETHRACE/common/spark.c
I cannot reproduce the original crash anymore
Fixes #132
> Re-enable `DrawTheGlow` 

- docs/PORTING.md
- src/DETHRACE/common/main.c
- src/DETHRACE/common/sound.c
- src/DETHRACE/constants.h
- src/DETHRACE/pc-dos/dossys.c
- src/S3/audio.c
- src/S3/audio.h
- src/S3/include/s3/s3.h
- src/S3/s3cda.c
- src/S3/s3cda.h
- src/S3/s3sound.c
- src/S3/s3sound.h
- src/harness/harness.c
- src/harness/include/harness/hooks.h
- src/harness/io_platforms/io_platform.h
- src/harness/io_platforms/sdl_gl.c
- `QuitGame` was only partially implemented
- Added extra S3 functions required for shutting down
- Moved S3 device opening functions to something more closely matching OG code
> Implements quitgame function

- src/DETHRACE/common/mainloop.c
Fixes 1 second hang per frame when playing action replay backwards
> Fixes slow reverse action replay playback

- src/DETHRACE/common/loading.c
- src/DETHRACE/common/netgame.c
- src/DETHRACE/common/racestrt.c
> Use DOS code for in-menu car icons

- lib/miniaudio/CMakeLists.txt
- src/DETHRACE/CMakeLists.txt
Tidies some clang flags.
Fixes #319
> Fixes #319

- src/DETHRACE/common/crush.c
- src/DETHRACE/common/crush.h
Adds the missing value to the `gSteal_ranks` array
> Fixes #357

- src/harness/win95/polyfill.c
> Don't leak file descriptors in GetFileAttributesA polyfill

- src/DETHRACE/common/utility.c
Fixes https://github.com/dethrace-labs/dethrace/issues/389
> Run QuitGame instead of DoSaveGame when quitting a game after pressing CTRL+Q

- src/harness/harness.c
- Adds `--window` to force windowed mode
> Full screen mode by default

- .gitmodules
Fix the url while we're at it.
> Update BRender-v1.3.2 a submodule

- src/DETHRACE/common/graphics.c
- src/DETHRACE/common/loadsave.c
- src/DETHRACE/common/utility.c
- src/DETHRACE/pc-dos/dossys.c
- src/DETHRACE/pc-win95/win95sys.c
- src/S3/s3sound.c
These were missing from the new platform code.
> Big endian fixes - part 2

- .github/workflows/workflow.yaml
Adds `libxext` on github ubuntu 24.x runner
> Adds missing lib for github build

- src/smackw32/include/smackw32/smackw32.h
- src/smackw32/smackw32.c
This fixes a case sensitivity issue on Linux
> smackw32: open SMK using harness

- .github/workflows/workflow.yaml
- reccmp/README.md
- src/DETHRACE/common/piping.c
`AdvanceChunkPtr` now 100% binary match
> Fixes AdvanceChunkPtr decomp
