src/DETHRACE/common/graphics.c

Implements ClearWobbles and replaces inlined code.
Cleans up floating point optimisations to use original divisions.

Refactors InitWobbleStuff.

---

src/BRSRC13/CMakeLists.txt
src/DETHRACE/CMakeLists.txt
src/DETHRACE/common/car.c
src/DETHRACE/common/displays.c
src/DETHRACE/common/mainloop.c
src/DETHRACE/common/mainmenu.c
src/DETHRACE/common/utility.c
src/S3/CMakeLists.txt
src/S3/s3sound.c
src/harness/CMakeLists.txt
src/harness/harness.c
src/harness/harness.h
src/harness/renderers/gl_renderer.c
src/harness/renderers/gl_renderer.h
src/harness/renderers/null_renderer.c
src/harness/stack_trace_handler.h

Adds `-Wall -Wextra -Werror` to all build dirs
Fixes `CleverText*` headup rendering by encoding extended ASCII chars as literals to avoid being turned into UTF-8

Enable more compiler errors

---

src/BRSRC13/CORE/FW/brlists.c
src/BRSRC13/CORE/FW/register.c
test/BRSRC13/test_brlists.c
test/BRSRC13/test_register.c

This pr implements all functions related to double linked lists, simple lists and registries.
The changes to the registry also fixes a bug:
the current implement does not allow to perform a `BrRegistryRemove` or `BrRegistryFind` on an empty registry.

Implement all functions related to lists + registries

---

src/BRSRC13/CORE/MATH/matrix23.c
src/BRSRC13/CORE/MATH/matrix34.c
src/BRSRC13/CORE/MATH/matrix4.c
src/BRSRC13/CORE/MATH/quat.c
test/BRSRC13/test_matrix23.c
test/BRSRC13/test_matrix34.c
test/BRSRC13/test_matrix4.c
test/BRSRC13/test_quat.c
test/CMakeLists.txt
test/main.c
test/tests.h

This pr adds implementations for all matrix related functions.
It also tests each function at least once.
fyi, the rolling ball algorithm is described in this paper:
http://citeseerx.ist.psu.edu/viewdoc/summary;jsessionid=FC5BB3EADECE14753EDF5C15AC6A1346?doi=10.1.1.69.2209
(equation 3 with nz = 0)

Implement all brender matrix functions

---

src/DETHRACE/common/input.c

The return value of `PDKeyDown2` was undefined. For me it resulted in always reporting that a key was pressed, leading to strange.... behavior in the UI :)

Fix PDKeyDown2

---

src/BRSRC13/CORE/V1DB/v1dbfile.c
src/harness/CMakeLists.txt
src/harness/include/harness/trace.h
src/harness/platforms/platform.h
src/harness/platforms/platform_linux.c
src/harness/platforms/platform_macosx.c
src/harness/platforms/platform_windows.c
src/harness/sdl/gl_renderer.c

This pr adds 2 main features to make our life easier:
- don't grab the mouse when a debugger is attached.
This means that, when debugging in an IDE, the mouse won't be hidden.
Right now, the mouse is hidden when some breakpoint is hit which is annoying.
- do `abort()` instead of `exit(1)` on a panic when a debugger is attached,
such that you are thrown right to the correct spot when e.g. an unimplemented function is encountered.
I copied the code to detect a debugger on Macos from this apple faq page: https://developer.apple.com/library/archive/qa/qa1361/_index.html
There is an important note about the code not working on a release build.
Since I don't own an apple (and you do), can you take a look at this and fix it?
You probably might have to `#ifdef _DEBUG` this function and return `0` …

Don't grab the mouse when debugging

---

src/DETHRACE/common/displays.c
src/DETHRACE/common/graphics.c
src/DETHRACE/common/pratcam.c
src/DETHRACE/common/racestrt.c
src/DETHRACE/common/structur.c

- Count checkpoints + checkpoints
- Fix flashing checkpoints in map mode
- Free taken pixelmap when leaving the change car dialog
(I wasn't able to get a screenshot of the race completed fancy headup)

Start checking checkpoints + laps

---

src/BRSRC13/CORE/MATH/matrix34.c
src/BRSRC13/CORE/V1DB/actsupt.c
src/BRSRC13/include/brender/brender.h
src/DETHRACE/common/car.c
src/DETHRACE/common/crush.c
src/DETHRACE/common/loading.c
src/DETHRACE/common/replay.c
src/DETHRACE/common/spark.c
src/DETHRACE/common/utility.c
src/harness/sdl/gl_brender_stored_context.c
src/harness/sdl/gl_brender_stored_context.h
src/harness/sdl/gl_renderer.c

- Implements: sparks, shrapnel, splash effects
- Fixes: incorrect depth buffer sorting with translucent materials
- Fixes: non-textured materials
- Fixes: `*RandomBetween` functions
https://user-images.githubusercontent.com/78985374/158077350-7f79a6a4-2074-40b6-b17c-43e18dc4ad52.mp4

Shrapnel and sparks

---

.github/workflows/workflow.yml
CMakeLists.txt
src/BRSRC13/CORE/FW/resource.c
src/DETHRACE/CMakeLists.txt
src/DETHRACE/common/car.c
src/DETHRACE/common/displays.c
src/DETHRACE/common/graphics.c
src/DETHRACE/common/loading.c
src/DETHRACE/common/mainloop.c
src/DETHRACE/common/pratcam.c
src/DETHRACE/common/spark.c
src/DETHRACE/pc-dos/dosnet.c
src/DETHRACE/pc-dos/dossys.c
src/harness/harness.c
test/BRSRC13/test_resource.c

- Fixes runtime errors when using debug runtime (`-MDd`/`-MTd`)
- Add 2 cmake options (`DETHRACE_IDE_ROOT_DIR` and  `DETHRACE_IDE_ARGUMENTS`) to enable debugging within MSVC.
- Fix the race timer counting down too fast when not frame limiting: the game would floor the frame period to 10ms.
Other fixes:
- fix bug in `ClearWobbles` + typo in `LoadGeneralParameters`
- use floats instead of doubles in varous places
- compare against `NULL`s
- stub `ChangeAmbientPratcamNow` so the game doesn't abort anymore when finishing/timing out.

Visual Studio Fixes

---

src/BRSRC13/CORE/FW/genfile.c
src/DETHRACE/common/car.c
src/DETHRACE/common/cutscene.c
src/DETHRACE/common/displays.c
src/DETHRACE/common/drfile.c
src/DETHRACE/common/flicplay.c
src/DETHRACE/common/graphics.c
src/DETHRACE/common/init.c
src/DETHRACE/common/loading.c
src/DETHRACE/common/mainloop.c
src/DETHRACE/common/spark.c
src/DETHRACE/common/structur.c
src/DETHRACE/common/utility.c
src/DETHRACE/common/utility.h
src/DETHRACE/common/world.c
src/DETHRACE/pc-dos/dossys.c
src/harness/harness.c
src/harness/include/harness/config.h

This pr:
- implements `DisposeTrack` (+depending functions). It is now possible to start a 2nd race in the same DethRace execution
- implement functions to support localized carmageddon releases: tested with a German localization
- fixes demo + text input for demo's
@laenion Can you test this?
The german version has the following issues:
- In all races, the HUD is hidden behind terrain (uk version also has this problem in e.g. fridge racer)
- in maim street, the front culling is too aggressive (the terrain is shown too late)
There is also a visual glitch with the umlaut on "neues spiel über netzwerk".
Comparing the data structures sizing the interface, there appears to be no difference between the uk and german release.
Is this also present when running the windows/dos version?
(the …

Dispose track after race + get german localization running

---

src/harness/harness.c

- Moves `FlushBuffers` to `EndScene` instead of `BrPixelmapDoubleBuffer`. In races without depth effects, flushing the 3d scene was happening _after_ 2d rendering, causing the 3d scene to appear in front of the HUD
- Fixes #125

Flush buffers in EndScene

---

src/BRSRC13/include/brender/br_inline_funcs.h
src/BRSRC13/include/brender/br_types.h
src/DETHRACE/common/car.c
src/DETHRACE/common/crush.c
src/DETHRACE/common/displays.c
src/DETHRACE/common/finteray.c
src/DETHRACE/common/loading.c
src/DETHRACE/common/world.c
src/DETHRACE/constants.h
src/DETHRACE/macros.h
src/harness/renderers/gl/gl_renderer.c

`NonCars` are what the game calls pieces of the track that you can interact with. For example, streetlights can be bent and snapped off, benches can be pushed around etc.
- Implements all the physics functions required for this to work
- Uncomments `RemoveDoubleSided`
- Fixes auto-generated `br_material` and `br_model` structs to align better with real usage
- Culling globally disabled in `gl_renderer` to fix issues with streetlights not rendering from all angles. This matches what we know of the 3dfx version, for example.
https://user-images.githubusercontent.com/78985374/166161286-42c78d9d-edb5-4844-8689-7d5af8a858e2.mp4

Implements "noncar" physics

---

src/BRSRC13/include/brender/br_defs.h
src/BRSRC13/include/brender/br_inline_funcs.h
src/DETHRACE/common/depth.c
src/DETHRACE/common/graphics.c
src/DETHRACE/common/init.c
src/DETHRACE/common/mainloop.c
src/DETHRACE/common/pedestrn.c
src/DETHRACE/common/raycast.c
src/DETHRACE/common/world.c
src/DETHRACE/constants.h

- Implements textured horizons
- Fixed some usage of `BR_ANGLE_DEG` which should be `BrDegreeToAngle`
1. First the back buffer is filled with one or more copies of the horizon texture, based on where the camera is pointing. 
2. Then, any gap at the top of the back buffer is filled with the color of the first pixel on the top row of the horizon texture
3. Then, any gap at the bottom of the back buffer is filled with the color of the first pixel on the bottom row of the horizon texture

Textured horizons

---

src/DETHRACE/common/intrface.c
src/DETHRACE/common/mainmenu.c
src/DETHRACE/common/racesumm.c
src/S3/audio.c
src/S3/include/s3/s3.h
src/harness/include/harness/hooks.h

- `FadePaletteDown` was used with an argument where it does not accept one
- `SoundService` does not accept an argument
- `Harness_Hook_BrV1dbRendererBegin` accepts `br_v1db_state* v1db`
There is still an issue with `S3IsCDAPlaying`, `S3IsCDAPlaying2` and `S3Set3DSoundEnvironment`.
But I'm hoping @dethrace-labs can address those.

Fix prototype(s) + function uses

---

CMakeLists.txt
src/BRSRC13/CMakeLists.txt
src/BRSRC13/CORE/FW/datafile.c
src/BRSRC13/include/brender/br_defs.h
src/BRSRC13/include/brender/br_types.h
src/DETHRACE/CMakeLists.txt
src/DETHRACE/common/flicplay.c
src/DETHRACE/common/loading.c
src/DETHRACE/common/loadsave.c
src/DETHRACE/common/utility.c
src/DETHRACE/pc-dos/dossys.c
src/S3/CMakeLists.txt
src/S3/s3sound.c
src/harness/CMakeLists.txt

This could be useful for porting Dethrace to XB360, PS3, Wii consoles, or perhaps more obscure platforms.

Big endian fixes

---

src/harness/io_platforms/sdl_gl.c
src/harness/renderers/gl/gl_renderer.c
src/harness/renderers/gl/shaders.c

With these changes, it is possible to start dethrace on
Pinebook Pro (Mali-T860 / Panfrost):
```
OpenGL vendor string: Panfrost
OpenGL renderer string: Mali-T860 (Panfrost)
OpenGL core profile version string: 3.1 Mesa 22.3.0-devel (git-d08bd9a8d8)
OpenGL core profile shading language version string: 1.40
```

gl: Relax GLSL requirement from 3.3 to 3.1

---

src/harness/os/windows.c

This unused `HANDLE` on `src/harness/os/windows.c` was failing the build on Windows.

remove unused Windows HANDLE

---

src/DETHRACE/common/displays.c
src/DETHRACE/common/displays.h
src/DETHRACE/common/init.c
src/DETHRACE/common/loading.c
src/DETHRACE/common/racestrt.c
src/DETHRACE/common/world.c

Since we now/soon will have aggressive opponents, I guess it's time to be able to empty our account and buy APO.
- Implement `DoAutoParts` and `DoPartsShop` dialog
- Change last argument of `TransBrPixelmapText` from `signed char*` to `char*`.
The latter makes more sense: `signed char` and `unsigned char` are types for numbers, char is for character data.
Removing the `signed` makes it possible to remove a few casts.
- Replaced some conditional tests to test against the proper types (no functional change)

Implement parts shop

---

src/DETHRACE/common/crush.c

This often caused the address sanitizer to decide for me the race is over :smile:

damage_magnitude_accumulator is only available when a car is oppo, net_human or local human

---

src/DETHRACE/common/opponent.c

After the for-loop preceding this array access, `section_no` was always set to the `section_no`.
Hence this would always access out-of-bounds.
Found by the trusty address sanitizer.

Use nearest_section in FindNearestGeneralSection

---

src/BRSRC13/include/brender/brender.h
src/DETHRACE/common/racesumm.c
src/DETHRACE/common/raycast.c

This pr implements the post-race "Damage Gallery".

Implement DoEndSummary2 (aka Damage Gallery)

---

src/BRSRC13/CORE/FW/resource.c
src/BRSRC13/include/brender/brender.h
src/DETHRACE/common/utility.c

The map "Industrial Action" references a pixelmap whose width is not a multiple of 4.
However, DethRace overrides the row stride to a multiple of 4 [here](https://github.com/dethrace-labs/dethrace/blob/f99be5f57a251f124a648fdca309460671ba93ab/src/DETHRACE/common/utility.c#L456) and [here](https://github.com/dethrace-labs/dethrace/blob/f99be5f57a251f124a648fdca309460671ba93ab/src/DETHRACE/common/utility.c#L472).
As a result of this, the GL renderer will do a buffer overread when [reading the pixels here](https://github.com/dethrace-labs/dethrace/blob/f99be5f57a251f124a648fdca309460671ba93ab/src/harness/renderers/gl/gl_renderer.c#L598-L604).
- To fix this, a helper function `align_pixelmap` is introduced that aligns each row.
- This pr also contains a patch for `resource.c` that extracts …

Fix address sanitizer error when loading "Industrial Action"

---

src/DETHRACE/common/pedestrn.c

Dropping a point in pedestrian edit mode would segfault otherwise.
`CARM95.EXE` also segfaults.
How to reproduce:
- enable Pedestrian edit mode
- F10 or F11 (+a few other)

Fix pedestrian edit functions segfaulting when path isn't created

---

src/DETHRACE/common/opponent.c

This is called primarily when an opponent falls off the world.
Fixes #156

Implements TeleportOpponentToNearestSafeLocation

---

src/DETHRACE/common/utility.c
test/DETHRACE/test_utility.c

Fix `IRandomBetween` returning numbers outside of the requested range.
e.g.:
```python
>>> pA = -5
>>> pB = -1
>>> r = 30701
>>> (pB + 1 - pA) * (30701 / (0x7fff+1)) + pA
-0.315399169921875
>>> int(_)
0
```
This fixes a potential stack overflow:
```
S3GetDescriptorByID audio.c:1102
S3GetDescriptorByID audio.c:1102
S3GetDescriptorByID audio.c:1102
S3GetDescriptorByID audio.c:1102
S3GetDescriptorByID audio.c:1102
S3GetDescriptorByID audio.c:1102
S3GetDescriptorByID audio.c:1102
S3GetDescriptorByID audio.c:1102
S3GetDescriptorByID audio.c:1102
S3GetDescriptorByID audio.c:1102
S3GetDescriptorByID audio.c:1102
S3GetDescriptorByID audio.c:1102
S3StartSound3D 3d.c:408
DRS3StartSound3D sound.c:514
CrashNoise car.c:3059
CollCheck car.c:2817
CollideCarWithWall car.c:1328
MoveAndCollideNonCar …
```

Fix IRandomBetween returning out-of-range numbers

---

src/BRSRC13/CORE/PIXELMAP/pmfile.c

Fixes #166
This is a bit risky if some texture contains a nonsense row_bytes value, caused by bugged authoring software.
But that is luckily (currently) not the case :smile:

Fix skewed cockpit

---

src/DETHRACE/common/world.c

This fixes a `Bad resource header from user` error I received when testing DethRace with [The MELD PACK](https://rr2000.cwaboard.co.uk/carmageddon-1).
Running with the address sanitizer, I was able to pin point the error immediately.

Fix buffer overload when loading more then 100 pixelmaps on 64-bit system

---

CMakeLists.txt
src/DETHRACE/common/car.c
src/harness/harness.c

- This was a regression caused by incorrect refactoring (by me in https://github.com/dethrace-labs/dethrace/pull/122)
- Fixes #157

Fix damage not being applied when hitting walls

---

.github/scripts/build-linux.sh
src/harness/os/linux.c

I noticed the stacktraces printed by our release only contained addresses and no file names + line numbers.
Running `file` on a released ELF and comparing with a locally built one gave the following:
**Release** -> "bad" stacktrace
```
dethrace: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=90bc4091d54dbbc6b6e890873a7988cf8d8172aa, for GNU/Linux 3.2.0, with debug_info, not stripped
```
**Local one** -> "good" stacktrace
```
dethrace: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=04916cbf9a5e87fb591ed2fe95a21262b2667566, for GNU/Linux 3.2.0, with debug_info, not stripped
```
Adding `-DCMAKE_C_FLAGS=-pie …

Fix signal handler for pie executables

---

src/DETHRACE/common/car.c
src/DETHRACE/common/pedestrn.c

This fixes hitting pedestrians in situations where they shouldn't be hit.
I think this might fix https://github.com/dethrace-labs/dethrace/issues/186, but this needs verification.
How to test this pr:
Enable molemode and float (close) above power-up/pedestrian.
Before, the power-up/pedestrians would be hit.
After, they are only hit when you touch them.

Fix pedestrian collision when floating very close to ped

---

src/DETHRACE/common/car.c

Fix segfault in coll check

---

src/DETHRACE/common/opponent.c

Implement ProcessLevitate

---

src/DETHRACE/common/car.c
src/DETHRACE/common/controls.c
src/DETHRACE/common/crush.c
src/DETHRACE/common/depth.c

Car damage after a race was not repaired because `TotallyRepairCar` was not implemented.
This pr implements that function + 3 other functions of which a message was printed.
Fixes #184

Add totally repair car

---

src/DETHRACE/common/racestrt.c

Technically, text is still drawn over older text. But now old text is completely obscured by new text.
Fixes #199

Fix y-alignment of numbers in parts shop

---

.github/workflows/workflow.yaml
src/DETHRACE/common/errors.c
src/DETHRACE/common/graphics.c
src/DETHRACE/common/intrface.c
src/DETHRACE/common/loading.c
src/DETHRACE/common/opponent.c
src/harness/harness.c
src/harness/include/harness/config.h
src/harness/include/harness/trace.h
src/harness/renderers/gl/gl_renderer.c

- disable diagnostics by default (`--enable-diagnostics` command line parameter to enable)
- print OpenGL information strings 
- remove random debug log lines that are not longer useful

Tidy up debug logging

---

src/BRSRC13/CORE/DOSIO/dosio.c
src/DETHRACE/common/globvars.c
src/DETHRACE/common/graphics.c
src/DETHRACE/pc-dos/dossys.c
src/harness/harness.c
src/harness/include/harness/hooks.h
src/harness/io_platforms/sdl_gl.c
src/harness/renderers/gl/gl_renderer.c
src/harness/renderers/gl/gl_renderer.h
src/harness/renderers/null.h
src/harness/renderers/renderer.h

Implements support for `-hires` command line arg rendering at 640x480 and using more detailed pixmaps from the `64x48x8` directory.
Fixes #159

Original "high resolution" support

---

src/DETHRACE/common/displays.c
src/DETHRACE/common/opponent.c
src/DETHRACE/common/racestrt.c

- Avoid negative arguments to `DRPixelmapRectangleShearedCopy` in `DoHeadups`
- Wrong end of loop condition in `MungeOpponents`
- Avoid writing out of bounds in `DrawGrid`

Fix of 3 little issues found with the undefined behavior sanitizer

---

src/DETHRACE/common/mainloop.c

Disable the arrow at the end of the race.

Splatpack x-mas demo executes ToggleArrow when the race finished

---

src/harness/renderers/gl/gl_renderer.c

The cause of #187 is weird track geometry where two back-facing triangles with no texture are laid on top of two front-facing textured triangles. The OG game culls the back-facing triangle, so it is not visible in game. (Ref: https://twitter.com/toshiba_3/status/1584152161386389504?s=20&t=g1bQ8KAAtKvn2zy1Qw6PUw)
As we are not culling, we render the back facing triangles, which causes the appearance of a missing texture in that part of the track!
We originally removed culling because it caused sides of streetlight poles to be invisible when viewed from the rear. Since then, we fixed/implemented `RemoveDoubleSided` which causes every face with a `BR_MATF_TWO_SIDED` material to be duplicated and faced backwards. We can now cull back faces without any apparent graphical issues.
Fixes: #187

Re-enables back face culling

---

src/S3/3d.c
src/S3/audio.c
src/S3/s3sound.c
src/harness/harness.c
src/harness/include/harness/config.h

- Fixes sounds should be stopped when the emitter is too far way (weren't calling `S3UpdateSoundSource` inside `S3Service`)
- Fixes DirectSound decibels to linear conversion by using `ma_volume_db_to_linear` 
- Adds `--volume-multiplier` command line arg to set overall volume gain. (windows seems to match OG, on OSX the audio seems too loud at the default gain of 1.0

Fix sounds

---

src/DETHRACE/common/loading.c

Fixes #178 
For more background;
https://www.cwaboard.co.uk/viewtopic.php?p=158796

Disable invalid groove bindings at end of LoadCar()

---

src/DETHRACE/common/skidmark.c

Don't reset skidmark normal to the horizontal plane, but rather use the one received from the wheel.
This fixes incorrect rendering of skidmarks on sloped surfaces (#220).
Before:
https://user-images.githubusercontent.com/510643/200192096-4ade21ad-a683-42af-9394-59016e16c75f.mp4
After:
https://user-images.githubusercontent.com/510643/200192095-d70e2e9b-5793-4a08-96d4-caac67d1d604.mp4

Fix skidmark orientation

---

.github/scripts/build-linux.sh
.github/scripts/build-macos.sh
.github/scripts/build-msvc.ps1
.github/workflows/workflow.yaml
src/DETHRACE/common/car.c
src/DETHRACE/common/controls.c
src/DETHRACE/common/opponent.c
src/DETHRACE/common/world.c

Fixes a few ci warnings (which were bugs) + other bugs + use brender macros for br_vector3 manipulation
About the ::set-output deprecation,
see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Fix ci warnings

---

src/DETHRACE/common/loading.c

Fix OG bug, where APC car would have its vertices and faces removed, preventing it from being rendered in the wreck gallery. Fixes #208

Show Squad Car in the wreck gallery

---

CMakeLists.txt
src/BRSRC13/CORE/V1DB/prepmesh.c
src/DETHRACE/CMakeLists.txt
src/DETHRACE/common/car.c
src/DETHRACE/common/cutscene.c
src/DETHRACE/common/init.c
src/DETHRACE/common/loading.c
src/DETHRACE/common/loadsave.c
src/DETHRACE/common/main.c
src/DETHRACE/common/mainloop.c
src/DETHRACE/common/mainmenu.c
src/DETHRACE/common/newgame.c
src/DETHRACE/common/racestrt.c
src/DETHRACE/common/racesumm.c
src/DETHRACE/common/spark.c
src/DETHRACE/common/structur.c
src/DETHRACE/common/utility.c
src/DETHRACE/common/world.c
src/harness/CMakeLists.txt
src/harness/harness.c
src/harness/include/harness/config.h
src/harness/io_platforms/sdl_gl.c
test/DETHRACE/test_utility.c
tools/decode_datatxt.py

- Fix crash at the end of a race when playing the splatpack (non-xmas) demo: the splatpack demo plays a smk, whereas the xmas demo displays a flic
- Simplify a few functions by switching if/else branches to reduce indentation and using `BrXXX` functions/macro's
- Fix `DecodeLine2` + `tools/decode_datatxt.py` so the coments become readable
- Implement `StopGroovidelic`
- Implement `TestAutoSpecialVolume: this increases the drag underwater
Fixes #194 
- I removed the stub in `DrawTheGlow`.
This change might be a bit controversial as it might introduces more crashes.
But I think this is good so we can find the bug sooner.
Either case, the crash in `SmokeLine` happens on my system too with stubbing this function.
- Fix address sanitizer warning when riding the APC car
- add `--full-screen` …

Fixes + add TestAutoSpecialVolume (=underwater)

---

src/DETHRACE/common/oil.c
src/harness/renderers/gl/gl_renderer.c

Due to the wrong order of vertices in the model, oil spill object is subject to back face culling, preventing it from being rendered. Make the oil spill front faced w/ regards to the floor.
Note: Setting `BR_MATF_TWO_SIDED` for the material flags does not solve this problem - the oil spill is still invisible. Has the original order of vertices been taken from OG disassembly?

Fix oil spill rendering

---

src/DETHRACE/common/graphics.c
src/DETHRACE/common/pedestrn.c

Only animate the respawn when we are in viewing distance.
This is done such that the "Peds visible on map" powerup draws far away items.
Far away animated pedestrians would otherwise remain invisible on the map until we get close to them.
Fixes #206

When respawning pedestrians, only animate nearby pedestrians

---

src/DETHRACE/common/spark.c

Fixes #241
SmudgeCar modifies the "darkness" of vertices of the prepared model.
I'm not 100% confident the GL renderer will use these updates vertices since no `BrModelUpdate` is called.
Or the renderern does not respect the darkness.

Implement SmudgeCar

---

src/DETHRACE/common/car.c
src/DETHRACE/common/world.c
src/DETHRACE/constants.h

Suspension was actually not working at all. An error was obvious in #221, but actually was a general suspension problem and not  a problem with jelly suspension powerup.
The main fix is inside the “straight” handling in PathGrooveBastard, with some unrelated fixes for “circular” that I noticed at the same time. Plus random float fixes as usual.
fixes #221  
https://user-images.githubusercontent.com/78985374/203441958-2a8acba6-c179-47b8-a21a-fd3edf99af0a.mov

Fix vehicle suspension so that it actually works

---

src/DETHRACE/common/racestrt.c

Mouse cursor is supposed to be hidden for a moment when scrolling through the driver info screen.
This fixes https://github.com/dethrace-labs/dethrace/issues/121.

Hide mouse cursor when scrolling driver info

---

src/DETHRACE/common/displays.c

Fix misaligned gear mask and a buffer overflow for cars which use more than 8 gears, and thus pixelmaps other than HGEARS.PIX.
This issue exists because the gear rendering code assumes that the pixelmap with gear images contains 8 individual gear images. However, this is only true for HGEARS.PIX. In case of the Suppressor, which uses HGEARS4.PIX, there are 11 gears and so the mask is applied at the wrong offset.
Since both of the pixelmaps in question have gears that should clip at the height of 28, hardcode this number instead of trying to calculate it.
Another solution would be to simply force HGEARS4.PIX for all the cars, as those graphics are identical for both files (just with more gears in the latter one). I guess they really wanted to save every byte of memory in the OG, huh?
This …

Fix gear rendering for Suppressor

---

src/harness/os/linux.c

The Linux implementation of `OS_fopen` fails to close directories after use, leaking the underlying file descriptors. Eventually, the limit of allowed file descriptors per process is reached, causing subsequent `opendir` failures, and leading to random game crashes.
Fix this issue by calling `closedir` once the directory can be disposed.
This fixes https://github.com/dethrace-labs/dethrace/issues/264.

Fix fd memory leak on Linux

---

src/DETHRACE/common/displays.c

Store the previous time credit in `gLast_time_credit_amount` instead of `gLast_time_credit_headup`. The latter is supposed to hold the headup slot number and gets overwritten with `NewTextHeadupSlot` index, effectively capping the time credits at the value of `+13`.
This fixes https://github.com/dethrace-labs/dethrace/issues/182.

Fix time credit headup

---

src/DETHRACE/common/graphics.c

Screen effects such as smoke, sparks or electro-bastard ray need to be applied only after the 3D scene is rendered. Otherwise, they might end up rendered behind geometry on certain levels. Examples of such levels include "Fridge Racer" and "Drown in the Sumps", where said effects are rendered behind most geometry (except car shadows), and "Icing on the Quake", where they are obscured by translucent ice texture (see #214 for details).
Since my lack of access to symbolicated disassembly of the original game prevents me from checking whether the original game renders those effects before or after `BrZbSceneRenderEnd`, perhaps this is just a prelude to a bigger issue in the rendering pipeline.
With this change, smoke in "Drown in the Sumps" is now correctly rendered at the right Z position: …

Fix framebuffer effects

---

src/DETHRACE/common/graphics.c

Resolve a bug in `DRPixelmapRectangleShearedCopy`, where source pixelmap gets clipped along the shear, rather than vertically, at right-most edge of the destination pixelmap.
While at it, also eliminate duplicate code - this part introduces no logic changes.
This fixes https://github.com/dethrace-labs/dethrace/issues/251

Fix rendering of fancy headups

---

src/DETHRACE/common/racestrt.c

Fix OG bug where racers could be scrolled in other view modes, messing up the screen.
This fixes https://github.com/dethrace-labs/dethrace/issues/262.

Prevent clicking on racer scroll buttons when hidden

---

src/DETHRACE/common/displays.c

When searching for a particular headup slot, don't return on the first empty hole, but rather try to find if the matching slot is in use.
This resolves a bug where two headups of the same type could end up displayed on top of each other: https://github.com/dethrace-labs/dethrace/issues/267
Fix confirmed with OG disassembly.

Fix headup hole lookup

---

src/DETHRACE/common/displays.c

A different gear mask is being used for standard and hi-res modes. Supply a hardcoded mask value for standard resolution and detect the graphics mode.
This supplements the change in 49d8e963f44b26d0f21debf1152d4d322bff3095.
As this change hardcodes data dependent values, it has been verified with the following datasets:
* Carmageddon: standard res + hires
* Carmageddon Demo: standard res
* Splat Pack: standard res + hires
* Splat Pack Demo: standard res + hires

Fix gear rendering for standard resolution mode

---

src/DETHRACE/common/world.c

The "Ramp Rampage" and "Acid Reign" tracks don't contain any skidmark material metadata, preventing skidmarks from being displayed in those races. As a workaround, use skidmark information extracted from "MagnaChem Mayhem", a variation of the same track design.
This fixes https://github.com/dethrace-labs/dethrace/issues/259:

Fix rendering of skidmarks in INDUSTB tracks

---

src/DETHRACE/common/loading.c

Strip map height is a 16 bit value. Cast to `uint16_t *`, so that the upper 8 bits don't get lost.
This fixes cockpit image rendering for -hires mode, where said images have heights exceeding 255px.
This patch resolves part 2 of https://github.com/dethrace-labs/dethrace/issues/271.

Fix hires cockpit image display

---

src/DETHRACE/common/graphics.c
src/harness/harness.c
src/harness/renderers/gl/gl_renderer.c
src/harness/renderers/gl/gl_renderer.h
src/harness/renderers/renderer.h

- Blend Test map available here: https://rr2000.cwaboard.co.uk/carmageddon-1
- Fix is to ensure we have the latest framebuffer while processing an `index_blend` material.
The reason it wasn't fully working already is because dethrace made the assumption that blendable materials will only be seen in the separate explicit blending rendering pass. This particular track fails to detect columns (in `ExtractColumns`), so blended materials are rendered in the first pass. The framebuffer hadn't yet been uploaded back to the GPU, so nothing was blended.

Fixes Toshiba's blend test map

---

src/S3/CMakeLists.txt
src/S3/audio.c

If the sound has been muted (!gS3_enabled) during game data loading, it is then possible to unmute it during gameplay and request a sound effect which doesn't have a sample loaded (most prominent for pratcam sfx). While the code accommodates for such a case, it does it too late, triggering a NULL pointer dereference on platforms which feature memory protection. This bug is most likely an overlook from the DOS era.
Fix this by moving the sample NULL pointer check before its first use.
Signed-off-by: Artur Rojek <contact@artur-rojek.eu>

Fix NULL pointer dereference in S3StartSound (#284)

---

src/DETHRACE/common/spark.c

When `SmokeLine` is called through `DrawTheGlow`, the calculated shade table offset might result in a negative value. Subject to usual arithmetic conversions, it is then treated as a large unsigned array index. On 32-bit systems (e.g. OG builds for DOS, Windows 95), the pointer arithmetic overflows and produces a negative index access, simply grabbing game data a few bytes before the start of the table. On 64-bit platforms this instead results in page fault.
1. Keep table offset in a signed integer, making the negative values explicit. This provides OG behavior for 64-bit builds.
2. Optionally, cap all negative values at 0, preventing underflows.

Fix buffer under/overflows in `SmokeLine` (#132)

---

src/DETHRACE/common/utility.c

The generated shade tables in `DATA/SHADETAB` were missing a `.TAB` suffix.
Found while looking into #297.

utility: fix filename of generated shade table

---

src/DETHRACE/common/init.c
src/DETHRACE/common/skidmark.c
src/DETHRACE/pc-dos/dossys.c
src/harness/harness.c
src/harness/include/harness/config.h
src/harness/include/harness/os.h
src/harness/os/linux.c
src/harness/os/macos.c
src/harness/os/windows.c

- Running DethRace with `-robots` segfaulted because `strtok` modifies read-only data. I found this error weird, because non-zombie mode also modifies read-only data. Fix this by copying the read-only data to the stack before modification.
- The Carmageddon DOS version asks for a password to allow running DethRace with gore. Re-implement this behavior when starting DethRace with `--dos-mode`

Fix for running with -robots + implement DOS gore password check

---

src/DETHRACE/common/depth.c
src/DETHRACE/common/powerup.c

The "Drugs!" powerup is implemented in two different parts
- `TheEffectsOfDrugs` function which runs every frame that shuffles palette colors around  (already done)
- `DoDrugWobbleCamera` function which manipulates the camera matrix to make the 3d scene 'wobble'
Interestingly, `TheEffectsOfDrugs` only changes the first 224 palette entries, both in DOS and Windows releases. This is why in snowy maps, the ground (being mostly white, palette index 255) is unaffected.

Implements drugs powerup

---

src/BRSRC13/include/brender/brender.h
src/harness/renderers/gl/gl_renderer.c
src/harness/resources/3d_vert.glsl

Some windscreen materials (for example, Eagle 1, Grimm, Harry) have a `BR_MATF_ENVIRONMENT_L` flag, and are somehow reflective.
According to BRender docs, this flag describes a spherical environment map. https://rr2000.cwaboard.co.uk/R4/BRENDER/TEBK_43.HTM#HEADING331
Fixes: #307

Implements BRender environment mapping

---

src/harness/renderers/gl/gl_renderer.c
src/harness/resources/3d_frag.glsl

Removes unused reference to `u_material_index_range` uniform since it can be optimized away and cause `glGetUniformLocation` to fail.
Fixes #304

Remove references to `u_material_index_range`

---

src/harness/platforms/sdl_opengl.c
src/harness/renderers/gl/gl_renderer.c
src/harness/renderers/gl/gl_renderer.h

Part of the `tHarness_platform` set of function pointers is `void (*Renderer_FlushBuffers)();`. It does not take any arguments. We were assigning `GLRenderer_FlushBuffers` to that, which took a `tRenderer_flush_type` argument.
Because we were not providing the argument, its value was undefined and sometimes would appear to work and sometimes not.
fixes #310

Provide an argument to GLRenderer_FlushBuffer

---

src/DETHRACE/common/depth.c
src/DETHRACE/common/displays.c
src/DETHRACE/common/graphics.c
src/DETHRACE/common/piping.c
src/DETHRACE/common/replay.c
src/DETHRACE/common/world.c
src/DETHRACE/dr_types.h
src/S3/3d.c
src/S3/audio.c
src/harness/harness.c
src/harness/include/harness/config.h

This fixes buffer a overflow in action replay, when the car has been damaged.
It also fixes a bonus overflow (catched with asan), + more debug checks for piping.
Because replay behaves more stable and much faster, the patch removes the `--enable-replay` option to enable replay. It is now always available.
The header of a session `{type; u8, count: u8}`. 
The number of chunks in a session was read wrong, most often it was 0xff on my system because heap pointers on my system (=Linux) look like `0x7ffff3aec800`.
Perhaps `malloc` behaves different on other platform because not everybody was seeing these crashes.
It fixes slow seeking in replay, and explains broken models.
This bug caused all deltas to be undone 255 times instead of 1 time.
It looks like only geometry and "hp" damage are …

Fix damaged cars in action replay

---

src/harness/os/macos.c

Stack traces work again with position independent code enabled.
```
******************
Caught SIGSEGV
******************
Stack trace:
0: GetALineAndDontArgue (in dethrace) (utility.c:325)
1: GetAFloat (in dethrace) (loading.c:2886)
2: LoadGeneralParameters (in dethrace) (loading.c:379)
3: InitialiseApplication (in dethrace) (init.c:356)
4: InitialiseDeathRace (in dethrace) (init.c:419)
5: GameMain (in dethrace) (main.c:123)
6: original_main (in dethrace) (win95sys.c:949)
7: main (in dethrace) (main.c:34)
```
inspired by https://github.com/mysql/mysql-server/blob/ea7087d885006918ad54458e7aad215b1650312c/storage/ndb/src/common/portlib/ndb_stacktrace.cpp#L76
Fixes #197

fixes stack traces on osx

---

src/DETHRACE/pc-win95/win95sys.c

PDKeyDown3 does not modify last_key_down and last_key_down_time
`PDKeyDown3` is used in the german DOS Carmageddon executable,
but not in the GOG splatpack Windows executable.
So I'm unsure what the correct approach is here.
Fixes #321

input: use PDKeyDown3 in PDGetASCIIFromKey

---

src/DETHRACE/common/sound.c

The initial value of `gOld_sound_detail_level` wasn't correctly copied from OG, so some of the code in `InitSound` was skipped if `SoundDetailLevel = 0`

Fixes #245

---

src/harness/harness.c
src/harness/include/harness/os.h
src/harness/os/linux.c
src/harness/os/macos.c
src/harness/os/windows.c
src/harness/renderers/gl/gl_renderer.c
src/harness/win95/polyfill.c

This patch uses `DETHRACE_ROOT_DIR` if defined, otherwise, uses the executable path to set the root directory
Fixes #308

chdir to exe path

---

src/DETHRACE/pc-win95/win95sys.c

The DOS version has a `-noreplay` option that disables replay.

Implement -noreplay from Carmageddon DOS version

---

src/harness/harness.c
src/harness/harness_trace.c
src/harness/include/harness/trace.h
src/harness/renderers/gl/gl_renderer.c

`argv[0]` was expected to include the full path to the dethrace executable. On windows, this is not true, and only includes the filename. 
As a fix, we should only try to `chdir` if `root_dir` is not empty or a single character.

Fix windows chdir behavior

---

src/DETHRACE/CMakeLists.txt
src/DETHRACE/common/car.c
src/DETHRACE/common/spark.c

Running with address sanitizer raised a couple of errors:
- `CollCheck` made some assumptions that the colliding object is a `tCar_spec`, when it could be a `tNon_car_spec`. 
- `CreateSplash` makes similar assumptions. 
A fairly reliable repro is to collide with the wrecked car next to the water in Maim Street and knock it into the water

Fix some Address Sanitizer errors

---

src/S3/s3music.c
src/harness/audio/miniaudio.c

`AudioBackend_StopCDA` doesn't call `ma_audio_unint` if the track has already finished playing. 
- Adds call to `ma_audio_unint` if necessary
- Adds call to `AudioBackend_StopCDA` inside `AudioBackend_PlayCDA` to ensure we are not still playing the previous track
Fixes #396

Fixes crash when not calling ma_audio_unint correctly

---

src/S3/s3sound.c
src/harness/audio/miniaudio.c

Incorporated the following changes:
1. Moved calls to `S3SyncSampleVolumeAndPan()` and `S3SyncSampleRate()` to follow call to `AudioBackend_PlaySample()`. This is required because the later one initializes the object on which `S3Sync...()` functions operate.
2. Removed a call to `ma_volume_db_to_linear()` as it expects input volume to be in exponential scale where `volume_db` is in linear scale. The call has been replaced with explicit transformation using reverse formula of the one found in `S3SyncSampleVolumeAndPan()` function.
Fixes #399

Fix 399: Game does not obey sound effects volume level set in sound settings.

---

src/DETHRACE/common/opponent.c

`finished_for_this_race` was set to `0` twice, and `has_moved_at_some_point` was not reset as well.
Fixes #401

Fix cops initialization in InitOpponents

---

src/smackw32/smackw32.c

LOGO.SMK contains no audio tracks at least in the US Interplay release, which could lead to SmackClose trying to access an uninitialized pointer when closing the audio stream.

Fix the playback of LOGO.SMK

---

src/DETHRACE/common/utility.c
src/harness/harness.c
src/harness/include/harness/config.h
src/harness/include/harness/hooks.h

This PR adds support for the Polish localized version of Carmageddon released in 2002 as a covermount disc for the Click! magazine. I added a wrapper to isalnum to deal with extended ASCII characters that can cause problems for the parser.

Polish localization support

---

src/DETHRACE/common/sound.c

First intention was to do a fix in a similar way like it has been fixed for effects volume. However, the "set-volume" request does not reach `S3SetCDAVolume()` function where caching of requested volume level could take place because it's stopped at `if (c->active)` [>>here<<](https://github.com/dethrace-labs/dethrace/blob/main/src/S3/s3.c#L1242).
As the fix enforced a change in original code, I decided to put it in a place where it's easier to understand. Other option was to do a fix in mentioned spot of S3.c file together with an implementation of deferred volume set in `S3SetCDAVolume()`, but that would change two files compared to one in proposed solution.

Ensure initial volume for CD music is properly set.

---

src/DETHRACE/common/racesumm.c

When player wants to look closer for a certain car in post race gallery (Wrecks Gallery) its model rotates by random angle when LMB is clicked. This change fixes the issue which is certainly a typo done during reverse engineering of code.

Fixed random rotation in Wrecks Gallery on first click

---

src/DETHRACE/common/pedestrn.c

Fix Showing Pedestrian Debug Paths

---

src/DETHRACE/common/mainloop.c
src/DETHRACE/common/opponent.c
src/DETHRACE/common/utility.c
src/DETHRACE/common/world.c

- 3dfx patch introduces a third debug info mode, showing detail about the closest material.
- Fixes calculation of `gBig_bang`
- Fixes `DRPixelmapHasZeros` which fixes rendering of black borders around hanging vines in Mayan Mayhem track

3dfx info mode

---

CMakeLists.txt
README.md
docs/CONFIGURATION.md
lib/inih/CMakeLists.txt
lib/inih/LICENSE.TXT
lib/inih/ini.c
lib/inih/ini.h
src/DETHRACE/common/structur.c
src/harness/CMakeLists.txt
src/harness/harness.c
src/harness/include/harness/config.h
src/harness/include/harness/hooks.h
src/harness/platforms/null.c
src/harness/platforms/sdl1.c
src/harness/platforms/sdl2.c
src/harness/platforms/sdl2_syms.h

- Looks for `dethrace.ini` in `SDL_GetPrefPath` location, and uses it. 
- Can specify a list of directories and nominate a default one.
1) Directory pointed to by DefaultGame
2) First game in the list if at least 1 game dir is specified
3) `DETHRACE_ROOT_DIR` environment variable
4) Current working directory (if `DATA/GENERAL.TXT` exists)
5) `SDL_GetPrefPath` directory
```
[General]
CdCheck = 0
GoreCheck = 0
FPSLimit = 60
; default demo time out is 240s (5 mins)
DemoTimeout = 240000
Windowed = 0
Emulate3DFX = 1
DefaultGame = c1demo
[Games]
sp = /opt/carma/c1sp
c1 = /opt/carma/c1
c1demo = /opt/carma/c1demo
[Cheats]
EditMode = 1
FreezeTimer = 0
GameCompleted = 0
[Sound]
Enabled = 1
SoundOptionsScreen = 1
VolumeMultiplier = 1
[Network]
NoBind = 0
AdapterName = ""
[Developers]
Diagnostics = 0 …
```

Ini file and fallback directories

---

src/DETHRACE/common/brucetrk.c
src/DETHRACE/common/car.c
src/DETHRACE/common/controls.c
src/DETHRACE/common/depth.c
src/DETHRACE/common/graphics.c
src/DETHRACE/common/loading.c
src/DETHRACE/common/netgame.c
src/DETHRACE/common/network.c
src/DETHRACE/common/newgame.c
src/DETHRACE/common/oil.c
src/DETHRACE/common/opponent.c
src/DETHRACE/common/options.c
src/DETHRACE/common/pedestrn.c
src/DETHRACE/common/piping.c
src/DETHRACE/common/powerup.c
src/DETHRACE/common/racestrt.c
src/DETHRACE/common/racesumm.c
src/DETHRACE/common/raycast.c
src/DETHRACE/common/sound.c
src/DETHRACE/common/spark.c
src/DETHRACE/common/utility.c
src/DETHRACE/common/world.c
src/DETHRACE/dr_types.h
src/DETHRACE/pc-all/net_types.h
src/DETHRACE/pc-none/nonet.c
src/S3/s3.c
src/library_brender.h
src/library_msvc.h

- AllocateActorMatrix
- PutOpponentsInNeutral
- TwoPointCollB
- CycleSoundDetailLevel
- InitDepthEffects
- MoreDepthFactor
- LessDepthFactor2
- AdjustRenderScreenSize
- InitializePalettes
- AmbientificateMaterial
- LoadGeneralParameters
- LoadInRegisteeDir
- DisposeCar
- OldDRfopen
- ReadNetworkSettings
- DeclareWinner
- FarEnoughAway
- NetSendHeadupToEverybody
- NetSendHeadupToPlayer
- RevertToDefaults
- DrawNetChoose
- InitOilSpills
- PointInSpill
- CalcPlayerConspicuousness
- ToggleOpponentProcessing
- DeleteNode
- DoPedestrian
- InitLastDamageArrayEtc
- SendCurrentPowerups
- AdjustSpark
- BuildSpecVolModel
Total effective accuracy 88.44% across 2369 functions (88.43% actual accuracy)

Reccmp batch 2

---

src/DETHRACE/common/car.c

Compiling with gcc 15, I had to fix these casts.
I don't think these casts change match accuracy.

Fix compile errors with modern gcc

---

src/DETHRACE/common/crush.c
src/DETHRACE/common/oil.c
src/DETHRACE/common/powerup.c

I noticed a few instances of NetBuildMessage that didn't use the NETMSG enums. Let me know if I missed any of them!

Replace leftover magic numbers with NETMSGID_* enums
